### ISSUE TITLE
Envo crashes when the inbox contains invalid JSON

### ISSUE THREAD

**Issue by phochste** [ErfgoedPod/evno#3]
Anything can be send to an inbox including JSON-LD. The envo command line tool crashes when none-JSON input is found in the inbox. See trace below.

Expected result would be to skip inbox entries that can't be parsed.

```
/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/jsonparse/jsonparse.js:90
  this.onError(new Error("Unexpected " + JSON.stringify(String.fromCharCode(buffer[i])) + " at position " + i + " in state " + Parser.toknam(this.tState)));
               ^

Error: Unexpected "S" at position 0 in state STOP
    at Parser.proto.charError (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/jsonparse/jsonparse.js:90:16)
    at Parser.proto.write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/jsonparse/jsonparse.js:154:23)
    at JsonLdParser._transform (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:122:25)
    at JsonLdParser.Transform._write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/transform.js:168:8)
    at writeOrBuffer (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/writable.js:341:12)
    at _write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
    at JsonLdParser.Writable.write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/writable.js:287:10)
    at Readable.ondata (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/li
```

**Comment by phochste** [comment]
Items that can't be parsed should still end up in a way in the cache database. Maybe the MD5 of the fetched text could be the cache db key

**Comment by mielvds** [comment]
Fixed by https://github.com/ErfgoedPod/evno/pull/5

**Comment by phochste** [comment]
The command line code still crashes when illegal data is read in the inbox

```
  this.onError(new Error("Unexpected " + JSON.stringify(String.fromCharCode(buffer[i])) + " at position " + i + " in state " + Parser.toknam(this.tState)));
               ^

Error: Unexpected "S" at position 0 in state STOP
    at Parser.proto.charError (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/jsonparse/jsonparse.js:90:16)
    at Parser.proto.write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/jsonparse/jsonparse.js:154:23)
    at JsonLdParser._transform (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/jsonld-streaming-parser/lib/JsonLdParser.js:122:25)
    at JsonLdParser.Transform._write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/transform.js:168:8)
    at writeOrBuffer (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/writable.js:341:12)
    at _write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
    at JsonLdParser.Writable.write (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/readable-stream/lib/internal/streams/writable.js:287:10)
    at Readable.ondata (node:internal/streams/readable:754:22)
    at Readable.emit (node:events:390:28)
    at Readable.emit (node:domain:475:12)
Emitted 'error' event on Receiver instance at:
    at Receiver.<anonymous> (file:///Users/hochsten/github.com/ErfgoedPod/evno/dist/receiver.js:153:30)
    at Generator.throw (<anonymous>)
    at rejected (/Users/hochsten/github.com/ErfgoedPod/evno/node_modules/tslib/tslib.js:116:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
